# Generated by Django 5.0.6 on 2024-05-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_clan_projekat'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekat',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='slike_projekta/'),
        ),
    ]
