# Generated by Django 5.0.6 on 2024-05-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_projekat_slika'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='email',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='slike_clanova/'),
        ),
    ]
