# Generated by Django 5.0.6 on 2024-05-25 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_clan_email_clan_slika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adresa', models.IntegerField()),
                ('ssh_username', models.CharField(max_length=20)),
                ('ssh_password', models.CharField(max_length=25)),
                ('ssh_port', models.IntegerField()),
                ('ime', models.CharField(max_length=18)),
                ('sistem_instaliran', models.TextField()),
                ('kreiran', models.DateTimeField(auto_now_add=True)),
                ('istice', models.DateField()),
                ('aktivna', models.BooleanField()),
                ('pristup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clan')),
            ],
        ),
    ]
