# Generated by Django 5.0.6 on 2024-05-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_masina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masina',
            name='ip_adresa',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='masina',
            name='pristup',
        ),
        migrations.AddField(
            model_name='masina',
            name='pristup',
            field=models.ManyToManyField(to='home.clan'),
        ),
    ]
